# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\ui_files\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # main window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 878)
        MainWindow.setAnimated(False)

        # central widget
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralWidget_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.centralWidget_layout.setContentsMargins(0, 0, 0, 0)
        self.centralWidget_layout.setSpacing(0)
        self.centralWidget_layout.setObjectName("centralWidget_layout")





        # side frame
        self.side_frame = QtWidgets.QFrame(self.centralwidget)
        self.side_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.side_frame.setMaximumSize(QtCore.QSize(0, 16777215))
        self.side_frame.setStyleSheet("")
        self.side_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.side_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_frame.setObjectName("side_frame")
        self.sideFrame_layout = QtWidgets.QVBoxLayout(self.side_frame)
        self.sideFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.sideFrame_layout.setSpacing(0)
        self.sideFrame_layout.setObjectName("sideFrame_layout")

        # application title frame
        self.application_title_frame = QtWidgets.QFrame(self.side_frame)
        self.application_title_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.application_title_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.application_title_frame.setStyleSheet(
            "background-color: rgb(25, 105, 170);\n"
            "color: rgb(220, 220, 220);"
        )
        self.application_title_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.application_title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.application_title_frame.setObjectName("application_title_frame")
        self.applicationTitleFrame_layout = QtWidgets.QVBoxLayout(self.application_title_frame)
        self.applicationTitleFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.applicationTitleFrame_layout.setSpacing(0)
        self.applicationTitleFrame_layout.setObjectName("applicationTitleFrame_layout")

        # application title label
        self.application_title = QtWidgets.QLabel(self.application_title_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.application_title.setFont(font)
        self.application_title.setAlignment(QtCore.Qt.AlignCenter)
        self.application_title.setObjectName("application_title")
        self.applicationTitleFrame_layout.addWidget(self.application_title)
        self.sideFrame_layout.addWidget(self.application_title_frame)

        # navagation frame
        self.navagation_frame = QtWidgets.QFrame(self.side_frame)
        self.navagation_frame.setStyleSheet(
            "QFrame{\n"
                "background-color: rgb(50, 50, 75);\n"
                "color: white;\n"
            "}\n"
            "QPushButton {\n"
                "border: none;\n"
                "background-color: rgb(50, 50, 75);\n"
                "color: white;\n"
            "}\n"
            "QPushButton:Hover {\n"
                "background-color: rgb(59, 61, 90);\n"
            "}"
        )
        self.navagation_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.navagation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navagation_frame.setObjectName("navagation_frame")
        self.navagationFrame_layout = QtWidgets.QVBoxLayout(self.navagation_frame)
        self.navagationFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.navagationFrame_layout.setSpacing(0)
        self.navagationFrame_layout.setObjectName("navagationFrame_layout")

        # applications page button
        self.applications_page_button = QtWidgets.QPushButton(self.navagation_frame)
        self.applications_page_button.setMinimumSize(QtCore.QSize(0, 60))
        self.applications_page_button.setMaximumSize(QtCore.QSize(16777215, 100000))
        self.applications_page_button.setStyleSheet(
            "background-color: rgb(33, 150, 243)"
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.applications_page_button.setFont(font)
        self.applications_page_button.setObjectName("applications_page_button")
        self.navagationFrame_layout.addWidget(self.applications_page_button)
        self.applications_page_button.clicked.connect(self.show_applications_page)

        # contacts page button
        self.contacts_page_button = QtWidgets.QPushButton(self.navagation_frame)
        self.contacts_page_button.setMinimumSize(QtCore.QSize(0, 60))
        self.contacts_page_button.setMaximumSize(QtCore.QSize(16777215, 100000))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.contacts_page_button.setFont(font)
        self.contacts_page_button.setObjectName("contacts_page_button")
        self.navagationFrame_layout.addWidget(self.contacts_page_button)
        self.contacts_page_button.clicked.connect(self.show_contacts_page)

        # questions page button
        self.questions_page_button = QtWidgets.QPushButton(self.navagation_frame)
        self.questions_page_button.setMinimumSize(QtCore.QSize(0, 60))
        self.questions_page_button.setMaximumSize(QtCore.QSize(16777215, 100000))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.questions_page_button.setFont(font)
        self.questions_page_button.setObjectName("questions_page_button")
        self.navagationFrame_layout.addWidget(self.questions_page_button)
        self.questions_page_button.clicked.connect(self.show_questions_page)

        # statistics page button
        self.statistics_page_button = QtWidgets.QPushButton(self.navagation_frame)
        self.statistics_page_button.setMinimumSize(QtCore.QSize(0, 60))
        self.statistics_page_button.setMaximumSize(QtCore.QSize(16777215, 100000))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statistics_page_button.setFont(font)
        self.statistics_page_button.setObjectName("statistics_page_button")
        self.navagationFrame_layout.addWidget(self.statistics_page_button)
        self.statistics_page_button.clicked.connect(self.show_statistics_page)

        # navagation frame bottom spacer
        spacerItem = QtWidgets.QSpacerItem(20, 551, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.navagationFrame_layout.addItem(spacerItem)
        self.sideFrame_layout.addWidget(self.navagation_frame)
        self.centralWidget_layout.addWidget(self.side_frame)





        # main frame
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("")
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.mainFrame_layout = QtWidgets.QVBoxLayout(self.main_frame)
        self.mainFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.mainFrame_layout.setSpacing(0)
        self.mainFrame_layout.setObjectName("mainFrame_layout")

        # stacked widget
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_frame)
        self.stackedWidget.setStyleSheet(
            "background-color: rgb(240, 240, 240);"
        )
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")





        # applications page
        self.applications_page = QtWidgets.QWidget()
        self.applications_page.setStyleSheet(
            "QPushButton {\n"
                "padding: 15px 35px;\n"
                "border: none;\n"
                "border-radius: 5px;\n"
                "background-color: rgb(33, 150, 243);\n"
                "color: white;\n"
            "}\n"
            "QPushButton:Hover {\n"
                "background-color: rgb(25, 105, 170);\n"
            "}\n"
            "QPushButton:Pressed {\n"
                "background-color: rgb(33, 150, 243);\n"
            "}"
        )
        self.applications_page.setObjectName("applications_page")
        self.applicationsPage_layout = QtWidgets.QVBoxLayout(self.applications_page)
        self.applicationsPage_layout.setContentsMargins(0, 0, 0, 0)
        self.applicationsPage_layout.setSpacing(0)
        self.applicationsPage_layout.setObjectName("applicationsPage_layout")

        # applications page header frame
        self.applications_header_frame = QtWidgets.QFrame(self.applications_page)
        self.applications_header_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.applications_header_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.applications_header_frame.setStyleSheet(
            "background-color: rgb(33, 150, 243);\n"
            "color: white;"
        )
        self.applications_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.applications_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.applications_header_frame.setObjectName("applications_header_frame")
        self.applicationsHeaderFrame_layout = QtWidgets.QVBoxLayout(self.applications_header_frame)
        self.applicationsHeaderFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.applicationsHeaderFrame_layout.setSpacing(0)
        self.applicationsHeaderFrame_layout.setObjectName("applicationsHeaderFrame_layout")

        # applications page title label
        self.applications_title = QtWidgets.QLabel(self.applications_header_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.applications_title.setFont(font)
        self.applications_title.setAlignment(QtCore.Qt.AlignCenter)
        self.applications_title.setObjectName("applications_title")
        self.applicationsHeaderFrame_layout.addWidget(self.applications_title)
        self.applicationsPage_layout.addWidget(self.applications_header_frame)

        # applications body frame
        self.applications_body_frame = QtWidgets.QFrame(self.applications_page)
        self.applications_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.applications_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.applications_body_frame.setObjectName("applications_body_frame")
        self.applicationsBodyFrame_layout = QtWidgets.QHBoxLayout(self.applications_body_frame)
        self.applicationsBodyFrame_layout.setContentsMargins(24, 24, 24, 24)
        self.applicationsBodyFrame_layout.setSpacing(24)
        self.applicationsBodyFrame_layout.setObjectName("applicationsBodyFrame_layout")

        # application filter outter frame
        self.application_filter_outter_frame = QtWidgets.QFrame(self.applications_body_frame)
        self.application_filter_outter_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.application_filter_outter_frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.application_filter_outter_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.application_filter_outter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.application_filter_outter_frame.setObjectName("application_filter_outter_frame")
        self.applicationFilterOutterFrame_layout = QtWidgets.QVBoxLayout(self.application_filter_outter_frame)
        self.applicationFilterOutterFrame_layout.setContentsMargins(0, 24, 0, 0)
        self.applicationFilterOutterFrame_layout.setSpacing(15)
        self.applicationFilterOutterFrame_layout.setObjectName("applicationFilterOutterFrame_layout")

        # application filter content group box
        self.application_filter_content_groupbox = QtWidgets.QGroupBox(self.application_filter_outter_frame)
        self.application_filter_content_groupbox.setMinimumSize(QtCore.QSize(200, 0))
        self.application_filter_content_groupbox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.application_filter_content_groupbox.setFont(font)
        self.application_filter_content_groupbox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.application_filter_content_groupbox.setStyleSheet(
            "QGroupBox {\n"
                "color: rgb(33, 150, 243);\n"
                "padding-top: 15px;\n"
            "}\n"
            "QLineEdit {\n"
                "border: 0px;\n"
                "background-color: white;\n"
            "}\n"
            "QComboBox {\n"
                "border: 0px;\n"
                "background-color: white;\n"
            "}\n"
            "QListView {\n"
                "background-color: white;\n"
            "}\n"
            "QGroupBox {\n"
                "border: 1px solid rgb(220, 220, 220);\n"
                "border-radius: 20px;\n"
            "}"
        )
        self.application_filter_content_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_filter_content_groupbox.setFlat(True)
        self.application_filter_content_groupbox.setCheckable(False)
        self.application_filter_content_groupbox.setObjectName("application_filter_content_groupbox")
        self.applicationFilterContentGroupbox_layout = QtWidgets.QVBoxLayout(self.application_filter_content_groupbox)
        self.applicationFilterContentGroupbox_layout.setContentsMargins(-1, 10, 9, 9)
        self.applicationFilterContentGroupbox_layout.setSpacing(12)
        self.applicationFilterContentGroupbox_layout.setObjectName("applicationFilterContentGroupbox_layout")

        # application company filter frame
        self.application_company_filter_frame = QtWidgets.QFrame(self.application_filter_content_groupbox)
        self.application_company_filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.application_company_filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.application_company_filter_frame.setObjectName("application_company_filter_frame")
        self.applicationCompanyFilterFrame_layout = QtWidgets.QVBoxLayout(self.application_company_filter_frame)
        self.applicationCompanyFilterFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.applicationCompanyFilterFrame_layout.setObjectName("applicationCompanyFilterFrame_layout")

        # application company filter label
        self.application_company_filter_label = QtWidgets.QLabel(self.application_company_filter_frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.application_company_filter_label.setFont(font)
        self.application_company_filter_label.setObjectName("application_company_filter_label")
        self.applicationCompanyFilterFrame_layout.addWidget(self.application_company_filter_label)

        # application company filter line edit
        self.application_company_filter_line_edit = QtWidgets.QLineEdit(self.application_company_filter_frame)
        self.application_company_filter_line_edit.setMinimumSize(QtCore.QSize(0, 25))
        self.application_company_filter_line_edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.application_company_filter_line_edit.setObjectName("application_company_filter_line_edit")
        self.applicationCompanyFilterFrame_layout.addWidget(self.application_company_filter_line_edit)
        self.applicationFilterContentGroupbox_layout.addWidget(self.application_company_filter_frame)

        # application position filter frame
        self.application_position_filter_frame = QtWidgets.QFrame(self.application_filter_content_groupbox)
        self.application_position_filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.application_position_filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.application_position_filter_frame.setObjectName("application_position_filter_frame")
        self.applicationPositionFilterFrame_layout = QtWidgets.QVBoxLayout(self.application_position_filter_frame)
        self.applicationPositionFilterFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.applicationPositionFilterFrame_layout.setObjectName("applicationPositionFilterFrame_layout")

        # application position filter label
        self.application_position_filter_label = QtWidgets.QLabel(self.application_position_filter_frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.application_position_filter_label.setFont(font)
        self.application_position_filter_label.setObjectName("application_position_filter_label")
        self.applicationPositionFilterFrame_layout.addWidget(self.application_position_filter_label)

        # application position filter line edit
        self.application_position_filter_line_edit = QtWidgets.QLineEdit(self.application_position_filter_frame)
        self.application_position_filter_line_edit.setMinimumSize(QtCore.QSize(0, 25))
        self.application_position_filter_line_edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.application_position_filter_line_edit.setObjectName("application_position_filter_line_edit")
        self.applicationPositionFilterFrame_layout.addWidget(self.application_position_filter_line_edit)
        self.applicationFilterContentGroupbox_layout.addWidget(self.application_position_filter_frame)

        # application city filter frame
        self.application_city_filter_frame = QtWidgets.QFrame(self.application_filter_content_groupbox)
        self.application_city_filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.application_city_filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.application_city_filter_frame.setObjectName("application_city_filter_frame")
        self.applicationCityFilterFrame_layout = QtWidgets.QVBoxLayout(self.application_city_filter_frame)
        self.applicationCityFilterFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.applicationCityFilterFrame_layout.setObjectName("applicationCityFilterFrame_layout")

        # application city filter label
        self.application_city_filter_label = QtWidgets.QLabel(self.application_city_filter_frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.application_city_filter_label.setFont(font)
        self.application_city_filter_label.setObjectName("application_city_filter_label")
        self.applicationCityFilterFrame_layout.addWidget(self.application_city_filter_label)

        # application city filter line edit
        self.application_city_filter_line_edit = QtWidgets.QLineEdit(self.application_city_filter_frame)
        self.application_city_filter_line_edit.setMinimumSize(QtCore.QSize(0, 25))
        self.application_city_filter_line_edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.application_city_filter_line_edit.setObjectName("application_city_filter_line_edit")
        self.applicationCityFilterFrame_layout.addWidget(self.application_city_filter_line_edit)
        self.applicationFilterContentGroupbox_layout.addWidget(self.application_city_filter_frame)

        # application state filter frame
        self.application_state_filter_frame = QtWidgets.QFrame(self.application_filter_content_groupbox)
        self.application_state_filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.application_state_filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.application_state_filter_frame.setObjectName("application_state_filter_frame")
        self.applicationStateFilterFrame_layout = QtWidgets.QVBoxLayout(self.application_state_filter_frame)
        self.applicationStateFilterFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.applicationStateFilterFrame_layout.setObjectName("applicationStateFilterFrame_layout")

        # application state filter label
        self.application_state_filter_label = QtWidgets.QLabel(self.application_state_filter_frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.application_state_filter_label.setFont(font)
        self.application_state_filter_label.setObjectName("application_state_filter_label")
        self.applicationStateFilterFrame_layout.addWidget(self.application_state_filter_label)

        # application state filter combo box
        self.application_state_filter_combo_box = QtWidgets.QComboBox(self.application_state_filter_frame)
        self.application_state_filter_combo_box.setMinimumSize(QtCore.QSize(0, 25))
        self.application_state_filter_combo_box.setMaximumSize(QtCore.QSize(16777215, 25))
        self.application_state_filter_combo_box.setStyleSheet("")
        self.application_state_filter_combo_box.setObjectName("application_state_filter_combo_box")
        for i in range(52):
            self.application_state_filter_combo_box.addItem("")
        self.applicationStateFilterFrame_layout.addWidget(self.application_state_filter_combo_box)
        self.applicationFilterContentGroupbox_layout.addWidget(self.application_state_filter_frame)

        # application status filter group box
        self.application_status_filter_groupbox = QtWidgets.QGroupBox(self.application_filter_content_groupbox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.application_status_filter_groupbox.setFont(font)
        self.application_status_filter_groupbox.setStyleSheet(
            "QGroupBox {\n"
                "padding-top: 0px;\n"
                "color: black;\n"
                "border-radius: 10px;\n"
            "}\n"
            "QCheckBox:Indicator:Unchecked {\n"
                "border: 1px solid rgb(220, 220, 220);\n"
                "border-radius: 2px;\n"
                "background-color: white;\n"
            "}"
        )
        self.application_status_filter_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.application_status_filter_groupbox.setFlat(True)
        self.application_status_filter_groupbox.setObjectName("application_status_filter_groupbox")
        self.applicationStatusFilterGroupBox_layout = QtWidgets.QVBoxLayout(self.application_status_filter_groupbox)
        self.applicationStatusFilterGroupBox_layout.setContentsMargins(-1, 20, -1, -1)
        self.applicationStatusFilterGroupBox_layout.setObjectName("applicationStatusFilterGroupBox_layout")

        # application submitted check box
        self.application_submitted_checkbox = QtWidgets.QCheckBox(self.application_status_filter_groupbox)
        self.application_submitted_checkbox.setAutoFillBackground(False)
        self.application_submitted_checkbox.setObjectName("application_submitted_checkbox")
        self.applicationStatusFilterGroupBox_layout.addWidget(self.application_submitted_checkbox)

        # screening interview check box
        self.screening_interview_checkbox = QtWidgets.QCheckBox(self.application_status_filter_groupbox)
        self.screening_interview_checkbox.setObjectName("screening_interview_checkbox")
        self.applicationStatusFilterGroupBox_layout.addWidget(self.screening_interview_checkbox)

        # technical interview check box
        self.technical_interview_checkbox = QtWidgets.QCheckBox(self.application_status_filter_groupbox)
        self.technical_interview_checkbox.setObjectName("technical_interview_checkbox")
        self.applicationStatusFilterGroupBox_layout.addWidget(self.technical_interview_checkbox)

        # job offer check box
        self.job_offer_check_box = QtWidgets.QCheckBox(self.application_status_filter_groupbox)
        self.job_offer_check_box.setObjectName("job_offer_check_box")
        self.applicationStatusFilterGroupBox_layout.addWidget(self.job_offer_check_box)

        # application rejected check box
        self.application_rejected_checkbox = QtWidgets.QCheckBox(self.application_status_filter_groupbox)
        self.application_rejected_checkbox.setObjectName("application_rejected_checkbox")
        self.applicationStatusFilterGroupBox_layout.addWidget(self.application_rejected_checkbox)
        self.applicationFilterContentGroupbox_layout.addWidget(self.application_status_filter_groupbox)
        self.applicationFilterOutterFrame_layout.addWidget(self.application_filter_content_groupbox)

        # application filter actions frame
        self.application_filter_actions_frame = QtWidgets.QFrame(self.application_filter_outter_frame)
        self.application_filter_actions_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.application_filter_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.application_filter_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.application_filter_actions_frame.setObjectName("application_filter_actions_frame")
        self.applicationFilterActionsFrame_layout = QtWidgets.QHBoxLayout(self.application_filter_actions_frame)
        self.applicationFilterActionsFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.applicationFilterActionsFrame_layout.setSpacing(0)
        self.applicationFilterActionsFrame_layout.setObjectName("applicationFilterActionsFrame_layout")

        # application filter actions frame left spacer
        application_filter_actions_frame_left_spacer = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.applicationFilterActionsFrame_layout.addItem(application_filter_actions_frame_left_spacer)

        # apply application filters button
        self.apply_application_filters_button = QtWidgets.QPushButton(self.application_filter_actions_frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.apply_application_filters_button.setFont(font)
        self.apply_application_filters_button.setObjectName("apply_application_filters_button")
        self.applicationFilterActionsFrame_layout.addWidget(self.apply_application_filters_button)

        # application filter actions frame right spacer
        application_filter_actions_frame_right_spacer = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.applicationFilterActionsFrame_layout.addItem(application_filter_actions_frame_right_spacer)
        self.applicationFilterOutterFrame_layout.addWidget(self.application_filter_actions_frame)

        # application filter outter frame spacer
        application_filter_outter_frame_spacer = QtWidgets.QSpacerItem(183, 234, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.applicationFilterOutterFrame_layout.addItem(application_filter_outter_frame_spacer)
        self.applicationsBodyFrame_layout.addWidget(self.application_filter_outter_frame)

        # application content frame
        self.application_content_frame = QtWidgets.QFrame(self.applications_body_frame)
        self.application_content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.application_content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.application_content_frame.setObjectName("application_content_frame")
        self.applicationContentFrame_layout = QtWidgets.QVBoxLayout(self.application_content_frame)
        self.applicationContentFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.applicationContentFrame_layout.setSpacing(24)
        self.applicationContentFrame_layout.setObjectName("applicationContentFrame_layout")

        # application table widget
        self.appications_table_widget = QtWidgets.QTableWidget(self.application_content_frame)
        self.appications_table_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.appications_table_widget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.appications_table_widget.setStyleSheet(
            "QTableWidget {\n"
                "border: 1px solid rgb(220, 220, 220);\n"
                "background-color: white;\n"
            "}\n"
            "QHeaderView:Section {\n"
                "height: 30px;\n"
                "border: none;\n"
                "background-color: rgb(33, 150, 243);\n"
                "color: white;\n"
            "}\n"
            "QTableWidget:Item {\n"
                "padding-left: 3px;\n"
            "}\n"
            "QTableView::Item {\n"
                "background-color: rgb(213, 230, 243);\n"
            "}\n"
            "QTableView::Item:Alternate {\n"
                "background-color: rgb(236, 240, 243);\n"
            "}\n"
            "QTableView::Item:Selected {\n"
                "background-color: rgb(25, 105, 170);\n"
            "}"
        )
        self.appications_table_widget.setLineWidth(1)
        self.appications_table_widget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.appications_table_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.appications_table_widget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.appications_table_widget.setAlternatingRowColors(True)
        self.appications_table_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.appications_table_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.appications_table_widget.setTextElideMode(QtCore.Qt.ElideRight)
        self.appications_table_widget.setShowGrid(False)
        self.appications_table_widget.setGridStyle(QtCore.Qt.SolidLine)
        self.appications_table_widget.setWordWrap(True)
        self.appications_table_widget.setCornerButtonEnabled(False)
        self.appications_table_widget.setRowCount(0)
        self.appications_table_widget.setObjectName("appications_table_widget")
        self.appications_table_widget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        # column 0 (company)
        self.appications_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.appications_table_widget.setColumnWidth(0, 300)
        # column 1 (position)
        self.appications_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.appications_table_widget.setColumnWidth(1, 300)
        # column 2 (location)
        self.appications_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.appications_table_widget.setColumnWidth(2, 300)
        # column 3 (status)
        self.appications_table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.appications_table_widget.setColumnWidth(3, 300)
        # column 4 (date)
        self.appications_table_widget.setHorizontalHeaderItem(4, item)
        self.appications_table_widget.horizontalHeader().setVisible(True)
        self.appications_table_widget.horizontalHeader().setCascadingSectionResizes(False)
        self.appications_table_widget.horizontalHeader().setStretchLastSection(True)
        self.appications_table_widget.verticalHeader().setStretchLastSection(False)
        self.applicationContentFrame_layout.addWidget(self.appications_table_widget)

        # application content actions frame
        self.application_content_actions_frame = QtWidgets.QFrame(self.application_content_frame)
        self.application_content_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.application_content_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.application_content_actions_frame.setObjectName("application_content_actions_frame")
        self.applicationContentActionsFrame_layout = QtWidgets.QHBoxLayout(self.application_content_actions_frame)
        self.applicationContentActionsFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.applicationContentActionsFrame_layout.setSpacing(24)
        self.applicationContentActionsFrame_layout.setObjectName("applicationContentActionsFrame_layout")

        # application content actions frame left spacer
        application_content_actions_frame_left_spacer = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.applicationContentActionsFrame_layout.addItem(application_content_actions_frame_left_spacer)

        # new application button
        self.new_application_button = QtWidgets.QPushButton(self.application_content_actions_frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.new_application_button.setFont(font)
        self.new_application_button.setObjectName("new_application_button")
        self.applicationContentActionsFrame_layout.addWidget(self.new_application_button)

        # view application button
        self.view_application_button = QtWidgets.QPushButton(self.application_content_actions_frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.view_application_button.setFont(font)
        self.view_application_button.setObjectName("view_application_button")
        self.applicationContentActionsFrame_layout.addWidget(self.view_application_button)

        # application content actions frame right spacer
        application_content_actions_frame_right_spacer = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.applicationContentActionsFrame_layout.addItem(application_content_actions_frame_right_spacer)

        # 
        self.applicationContentFrame_layout.addWidget(self.application_content_actions_frame)
        self.applicationsBodyFrame_layout.addWidget(self.application_content_frame)
        self.applicationsPage_layout.addWidget(self.applications_body_frame)
        self.stackedWidget.addWidget(self.applications_page)





        # Contacts Page
        self.contacts_page = QtWidgets.QWidget()
        self.contacts_page.setObjectName("contacts_page")
        self.contactsPage_layout = QtWidgets.QVBoxLayout(self.contacts_page)
        self.contactsPage_layout.setContentsMargins(0, 0, 0, 0)
        self.contactsPage_layout.setSpacing(0)
        self.contactsPage_layout.setObjectName("contactsPage_layout")

        # contacts header frame
        self.contacts_header_frame = QtWidgets.QFrame(self.contacts_page)
        self.contacts_header_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.contacts_header_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.contacts_header_frame.setStyleSheet(
            "background-color: rgb(196, 46, 68);\n"
            "color:white;"
        )
        self.contacts_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contacts_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contacts_header_frame.setObjectName("contacts_header_frame")
        self.contactsHeaderFrame_layout = QtWidgets.QVBoxLayout(self.contacts_header_frame)
        self.contactsHeaderFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.contactsHeaderFrame_layout.setSpacing(0)
        self.contactsHeaderFrame_layout.setObjectName("contactsHeaderFrame_layout")

        # contacts page title label
        self.contacts_title = QtWidgets.QLabel(self.contacts_header_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.contacts_title.setFont(font)
        self.contacts_title.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts_title.setObjectName("contacts_title")
        self.contactsHeaderFrame_layout.addWidget(self.contacts_title)
        self.contactsPage_layout.addWidget(self.contacts_header_frame)

        # contacts page body frame
        self.contacts_body_frame = QtWidgets.QFrame(self.contacts_page)
        self.contacts_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contacts_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contacts_body_frame.setObjectName("contacts_body_frame")
        self.contactsPage_layout.addWidget(self.contacts_body_frame)
        self.stackedWidget.addWidget(self.contacts_page)





        # question page
        self.questions_page = QtWidgets.QWidget()
        self.questions_page.setObjectName("questions_page")
        self.questionsPage_layout = QtWidgets.QVBoxLayout(self.questions_page)
        self.questionsPage_layout.setContentsMargins(0, 0, 0, 0)
        self.questionsPage_layout.setSpacing(0)
        self.questionsPage_layout.setObjectName("questionsPage_layout")

        # questions page header frame
        self.questions_header_frame = QtWidgets.QFrame(self.questions_page)
        self.questions_header_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.questions_header_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.questions_header_frame.setStyleSheet(
            "background-color: rgb(59, 84, 188);\n"
            "color: white;"
        )
        self.questions_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.questions_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.questions_header_frame.setObjectName("questions_header_frame")
        self.questionsHeaderFrame_layout = QtWidgets.QVBoxLayout(self.questions_header_frame)
        self.questionsHeaderFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.questionsHeaderFrame_layout.setSpacing(0)
        self.questionsHeaderFrame_layout.setObjectName("questionsHeaderFrame_layout")

        # questions page title label
        self.questions_title = QtWidgets.QLabel(self.questions_header_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.questions_title.setFont(font)
        self.questions_title.setAlignment(QtCore.Qt.AlignCenter)
        self.questions_title.setObjectName("questions_title")
        self.questionsHeaderFrame_layout.addWidget(self.questions_title)
        self.questionsPage_layout.addWidget(self.questions_header_frame)

        # questions page body frame
        self.questions_body_frame = QtWidgets.QFrame(self.questions_page)
        self.questions_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.questions_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.questions_body_frame.setObjectName("questions_body_frame")
        self.questionsPage_layout.addWidget(self.questions_body_frame)
        self.stackedWidget.addWidget(self.questions_page)





        # statistics page
        self.statistics_page = QtWidgets.QWidget()
        self.statistics_page.setObjectName("statistics_page")
        self.statisticsPage_layout = QtWidgets.QVBoxLayout(self.statistics_page)
        self.statisticsPage_layout.setContentsMargins(0, 0, 0, 0)
        self.statisticsPage_layout.setSpacing(0)
        self.statisticsPage_layout.setObjectName("statisticsPage_layout")

        # statistics page header frame
        self.statistics_header_frame = QtWidgets.QFrame(self.statistics_page)
        self.statistics_header_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.statistics_header_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.statistics_header_frame.setStyleSheet(
            "background-color: rgb(247, 84, 48);\n"
            "color: white;"
        )
        self.statistics_header_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statistics_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statistics_header_frame.setObjectName("statistics_header_frame")
        self.statisticsHeaderFrame_layout = QtWidgets.QVBoxLayout(self.statistics_header_frame)
        self.statisticsHeaderFrame_layout.setContentsMargins(0, 0, 0, 0)
        self.statisticsHeaderFrame_layout.setSpacing(0)
        self.statisticsHeaderFrame_layout.setObjectName("statisticsHeaderFrame_layout")

        # statistics page title label
        self.statistics_title = QtWidgets.QLabel(self.statistics_header_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.statistics_title.setFont(font)
        self.statistics_title.setAlignment(QtCore.Qt.AlignCenter)
        self.statistics_title.setObjectName("statistics_title")
        self.statisticsHeaderFrame_layout.addWidget(self.statistics_title)
        self.statisticsPage_layout.addWidget(self.statistics_header_frame)

        # statistics page body frame
        self.statistics_body_frame = QtWidgets.QFrame(self.statistics_page)
        self.statistics_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statistics_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statistics_body_frame.setObjectName("statistics_body_frame")
        self.statisticsPage_layout.addWidget(self.statistics_body_frame)
        self.stackedWidget.addWidget(self.statistics_page)





        # 
        self.mainFrame_layout.addWidget(self.stackedWidget)
        self.centralWidget_layout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        #
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.application_title.setText(_translate("MainWindow", "Job Application Vault"))
        self.applications_page_button.setText(_translate("MainWindow", "Applications"))
        self.contacts_page_button.setText(_translate("MainWindow", "Contacts"))
        self.questions_page_button.setText(_translate("MainWindow", "Questions"))
        self.statistics_page_button.setText(_translate("MainWindow", "Statistics"))
        self.applications_title.setText(_translate("MainWindow", "APPLICATIONS"))
        self.application_filter_content_groupbox.setTitle(_translate("MainWindow", "Filters"))
        self.application_company_filter_label.setText(_translate("MainWindow", "Company:"))
        self.application_position_filter_label.setText(_translate("MainWindow", "Position:"))
        self.application_city_filter_label.setText(_translate("MainWindow", "City:"))
        self.application_state_filter_label.setText(_translate("MainWindow", "State:"))
        self.application_state_filter_combo_box.setItemText(0, _translate("MainWindow", "-"))
        self.application_state_filter_combo_box.setItemText(1, _translate("MainWindow", "(Unknown)"))
        self.application_state_filter_combo_box.setItemText(2, _translate("MainWindow", "Alabama"))
        self.application_state_filter_combo_box.setItemText(3, _translate("MainWindow", "Alaska"))
        self.application_state_filter_combo_box.setItemText(4, _translate("MainWindow", "Arizona"))
        self.application_state_filter_combo_box.setItemText(5, _translate("MainWindow", "Arkansas"))
        self.application_state_filter_combo_box.setItemText(6, _translate("MainWindow", "California"))
        self.application_state_filter_combo_box.setItemText(7, _translate("MainWindow", "Colorado"))
        self.application_state_filter_combo_box.setItemText(8, _translate("MainWindow", "Connecticut"))
        self.application_state_filter_combo_box.setItemText(9, _translate("MainWindow", "Delaware"))
        self.application_state_filter_combo_box.setItemText(10, _translate("MainWindow", "Florida"))
        self.application_state_filter_combo_box.setItemText(11, _translate("MainWindow", "Georgia"))
        self.application_state_filter_combo_box.setItemText(12, _translate("MainWindow", "Hawaii"))
        self.application_state_filter_combo_box.setItemText(13, _translate("MainWindow", "Idaho"))
        self.application_state_filter_combo_box.setItemText(14, _translate("MainWindow", "Illinois"))
        self.application_state_filter_combo_box.setItemText(15, _translate("MainWindow", "Indiana"))
        self.application_state_filter_combo_box.setItemText(16, _translate("MainWindow", "Iowa"))
        self.application_state_filter_combo_box.setItemText(17, _translate("MainWindow", "Kansas"))
        self.application_state_filter_combo_box.setItemText(18, _translate("MainWindow", "Kentucky"))
        self.application_state_filter_combo_box.setItemText(19, _translate("MainWindow", "Louisiana"))
        self.application_state_filter_combo_box.setItemText(20, _translate("MainWindow", "Maine"))
        self.application_state_filter_combo_box.setItemText(21, _translate("MainWindow", "Maryland"))
        self.application_state_filter_combo_box.setItemText(22, _translate("MainWindow", "Massachusetts"))
        self.application_state_filter_combo_box.setItemText(23, _translate("MainWindow", "Michigan"))
        self.application_state_filter_combo_box.setItemText(24, _translate("MainWindow", "Minnesota"))
        self.application_state_filter_combo_box.setItemText(25, _translate("MainWindow", "Mississippi"))
        self.application_state_filter_combo_box.setItemText(26, _translate("MainWindow", "Missouri"))
        self.application_state_filter_combo_box.setItemText(27, _translate("MainWindow", "Montana"))
        self.application_state_filter_combo_box.setItemText(28, _translate("MainWindow", "Nebraska"))
        self.application_state_filter_combo_box.setItemText(29, _translate("MainWindow", "Nevada"))
        self.application_state_filter_combo_box.setItemText(30, _translate("MainWindow", "New Hampshire"))
        self.application_state_filter_combo_box.setItemText(31, _translate("MainWindow", "New Jersey"))
        self.application_state_filter_combo_box.setItemText(32, _translate("MainWindow", "New Mexico"))
        self.application_state_filter_combo_box.setItemText(33, _translate("MainWindow", "New York"))
        self.application_state_filter_combo_box.setItemText(34, _translate("MainWindow", "North Carolina"))
        self.application_state_filter_combo_box.setItemText(35, _translate("MainWindow", "North Dakota"))
        self.application_state_filter_combo_box.setItemText(36, _translate("MainWindow", "Ohio"))
        self.application_state_filter_combo_box.setItemText(37, _translate("MainWindow", "Oklahoma"))
        self.application_state_filter_combo_box.setItemText(38, _translate("MainWindow", "Oregon"))
        self.application_state_filter_combo_box.setItemText(39, _translate("MainWindow", "Pennsylvania"))
        self.application_state_filter_combo_box.setItemText(40, _translate("MainWindow", "Rhode Island"))
        self.application_state_filter_combo_box.setItemText(41, _translate("MainWindow", "South Carolina"))
        self.application_state_filter_combo_box.setItemText(42, _translate("MainWindow", "South Dakota"))
        self.application_state_filter_combo_box.setItemText(43, _translate("MainWindow", "Tennessee"))
        self.application_state_filter_combo_box.setItemText(44, _translate("MainWindow", "Texas"))
        self.application_state_filter_combo_box.setItemText(45, _translate("MainWindow", "Utah"))
        self.application_state_filter_combo_box.setItemText(46, _translate("MainWindow", "Vermont"))
        self.application_state_filter_combo_box.setItemText(47, _translate("MainWindow", "Virginia"))
        self.application_state_filter_combo_box.setItemText(48, _translate("MainWindow", "Washington"))
        self.application_state_filter_combo_box.setItemText(49, _translate("MainWindow", "West Virginia"))
        self.application_state_filter_combo_box.setItemText(50, _translate("MainWindow", "Wisconsin"))
        self.application_state_filter_combo_box.setItemText(51, _translate("MainWindow", "Wyoming"))
        self.application_status_filter_groupbox.setTitle(_translate("MainWindow", "Status:"))
        self.application_submitted_checkbox.setText(_translate("MainWindow", "Application Submitted"))
        self.screening_interview_checkbox.setText(_translate("MainWindow", "Screening Interview"))
        self.technical_interview_checkbox.setText(_translate("MainWindow", "Technical Interview"))
        self.job_offer_check_box.setText(_translate("MainWindow", "Job Offer"))
        self.application_rejected_checkbox.setText(_translate("MainWindow", "Application Rejected"))
        self.apply_application_filters_button.setText(_translate("MainWindow", "Apply"))
        self.appications_table_widget.setSortingEnabled(True)
        item = self.appications_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Company"))
        item = self.appications_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Position"))
        item = self.appications_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Location"))
        item = self.appications_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.appications_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        self.new_application_button.setText(_translate("MainWindow", "New Application"))
        self.view_application_button.setText(_translate("MainWindow", "View Application"))
        self.contacts_title.setText(_translate("MainWindow", "CONTACTS"))
        self.questions_title.setText(_translate("MainWindow", "QUESTIONS"))
        self.statistics_title.setText(_translate("MainWindow", "STATISTICS"))





    def show_applications_page(self):
         # Change page
        self.stackedWidget.setCurrentIndex(0)

        # Change application title frame's color
        self.application_title_frame.setStyleSheet(
            "background-color: rgb(25, 105, 170);\n"
            "color: rgb(220, 220, 220);"
        )

        # Change navagation's application button color
        self.applications_page_button.setStyleSheet(
            "background-color: rgb(33, 150, 243)"
        )

        # Revert unselected navagations' button colors
        self.contacts_page_button.setStyleSheet(
            ""
        )
        self.questions_page_button.setStyleSheet(
            ""
        )
        self.statistics_page_button.setStyleSheet(
            ""
        )

    def show_contacts_page(self):
        # Change page
        self.stackedWidget.setCurrentIndex(1)

        # Change application title frame's color
        self.application_title_frame.setStyleSheet(
            "background-color: rgb(137, 28, 48);\n"
            "color: rgb(220, 220, 220);"
        )

        # Change navagation's contact button color
        self.contacts_page_button.setStyleSheet(
            "background-color: rgb(196, 46, 68)"
        )

        # Revert unselected navagations' button colors
        self.applications_page_button.setStyleSheet(
            ""
        )
        self.questions_page_button.setStyleSheet(
            ""
        )
        self.statistics_page_button.setStyleSheet(
            ""
        )

    def show_questions_page(self):
        # Change page
        self.stackedWidget.setCurrentIndex(2)

        # Change application title frame's color
        self.application_title_frame.setStyleSheet(
            "background-color: rgb(44, 58, 130);\n"
            "color: rgb(220, 220, 220);"
        )

        # Change navagation's question button color
        self.questions_page_button.setStyleSheet(
            "background-color: rgb(59, 84, 188)"
        )

        # Revert unselected navagations' button colors
        self.applications_page_button.setStyleSheet(
            ""
        )
        self.contacts_page_button.setStyleSheet(
            ""
        )
        self.statistics_page_button.setStyleSheet(
            ""
        )

    def show_statistics_page(self):
        # Change page
        self.stackedWidget.setCurrentIndex(3)

        # Change application title frame's color
        self.application_title_frame.setStyleSheet(
            "background-color: rgb(172, 58, 32);\n"
            "color: rgb(220, 220, 220);"
        )

        # Change navagation's question button color
        self.statistics_page_button.setStyleSheet(
            "background-color: rgb(247, 84, 48)"
        )

        # Revert unselected navagations' button colors
        self.applications_page_button.setStyleSheet(
            ""
        )
        self.contacts_page_button.setStyleSheet(
            ""
        )
        self.questions_page_button.setStyleSheet(
            ""
        )