from PyQt5.QtCore import Qt, QMetaObject, QCoreApplication, QSize, QDateTime, QDate, QTime, QRect
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import (
    QWidget, QTableWidget, QTableWidgetItem,
    QFrame, QGroupBox,
    QLabel, QSpacerItem,
    QPushButton, QLineEdit, QPlainTextEdit, QComboBox, QDateTimeEdit, QDateEdit,
    QHBoxLayout, QVBoxLayout, QSizePolicy,
    QScrollArea, QAbstractSpinBox,
    QApplication, QMainWindow
)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 706)
        MainWindow.setMinimumSize(QSize(450, 400))
        MainWindow.setMaximumSize(QSize(450, 900))
        MainWindow.setStyleSheet("")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget_layout = QVBoxLayout(self.centralwidget)
        self.centralwidget_layout.setContentsMargins(0, 0, 0, 0)
        self.centralwidget_layout.setSpacing(0)
        self.centralwidget_layout.setObjectName("centralwidget_layout")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 431, 1522))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrikkAreaWidgetContents_layout = QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrikkAreaWidgetContents_layout.setContentsMargins(0, 0, 0, 0)
        self.scrikkAreaWidgetContents_layout.setSpacing(0)
        self.scrikkAreaWidgetContents_layout.setObjectName("scrikkAreaWidgetContents_layout")
        self.application_title_frame = QFrame(self.scrollAreaWidgetContents)
        self.application_title_frame.setMinimumSize(QSize(0, 80))
        self.application_title_frame.setMaximumSize(QSize(16777215, 80))
        self.application_title_frame.setStyleSheet("color: white;\n"
"background-color: rgb(50, 50, 75);")
        self.application_title_frame.setFrameShape(QFrame.StyledPanel)
        self.application_title_frame.setFrameShadow(QFrame.Raised)
        self.application_title_frame.setObjectName("application_title_frame")
        self.verticalLayout = QVBoxLayout(self.application_title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.application_title_label = QLabel(self.application_title_frame)
        self.application_title_label.setMinimumSize(QSize(0, 0))
        self.application_title_label.setMaximumSize(QSize(16777215, 16777215))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.application_title_label.setFont(font)
        self.application_title_label.setAlignment(Qt.AlignCenter)
        self.application_title_label.setObjectName("application_title_label")
        self.verticalLayout.addWidget(self.application_title_label)
        self.scrikkAreaWidgetContents_layout.addWidget(self.application_title_frame)
        self.application_body_frame = QFrame(self.scrollAreaWidgetContents)
        self.application_body_frame.setStyleSheet("#application_body_frame {\n"
"background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QGroupBox {\n"
"border: 1px solid rgb(220, 220, 220);\n"
"border-radius: 20px;\n"
"padding-top: 15px;\n"
"color: rgb(33, 150, 243);\n"
"}\n"
"\n"
"QLineEdit, QComboBox, QPlainTextEdit, QTableWidget {\n"
"border: 0px;\n"
"}\n"
"\n"
"QPushButton {\n"
"padding: 5px 15px;\n"
"border: none;\n"
"border-radius: 5px;\n"
"background-color: rgb(33, 150, 243);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:Hover {\n"
"background-color: rgb(25, 105, 170);\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(33, 150, 243);\n"
"}")
        self.application_body_frame.setFrameShape(QFrame.StyledPanel)
        self.application_body_frame.setFrameShadow(QFrame.Raised)
        self.application_body_frame.setObjectName("application_body_frame")
        self.verticalLayout_13 = QVBoxLayout(self.application_body_frame)
        self.verticalLayout_13.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout_13.setSpacing(24)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.company_details_group_box = QGroupBox(self.application_body_frame)
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.company_details_group_box.setFont(font)
        self.company_details_group_box.setFlat(True)
        self.company_details_group_box.setObjectName("company_details_group_box")
        self.verticalLayout_5 = QVBoxLayout(self.company_details_group_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.company_frame = QFrame(self.company_details_group_box)
        self.company_frame.setFrameShape(QFrame.StyledPanel)
        self.company_frame.setFrameShadow(QFrame.Raised)
        self.company_frame.setObjectName("company_frame")
        self.verticalLayout_2 = QVBoxLayout(self.company_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.company_label = QLabel(self.company_frame)
        self.company_label.setObjectName("company_label")
        self.verticalLayout_2.addWidget(self.company_label)
        self.company_line_edit = QLineEdit(self.company_frame)
        self.company_line_edit.setMinimumSize(QSize(0, 25))
        self.company_line_edit.setMaximumSize(QSize(16777215, 25))
        self.company_line_edit.setObjectName("company_line_edit")
        self.verticalLayout_2.addWidget(self.company_line_edit)
        self.verticalLayout_5.addWidget(self.company_frame)
        self.city_frame = QFrame(self.company_details_group_box)
        self.city_frame.setFrameShape(QFrame.StyledPanel)
        self.city_frame.setFrameShadow(QFrame.Raised)
        self.city_frame.setObjectName("city_frame")
        self.verticalLayout_3 = QVBoxLayout(self.city_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.city_label = QLabel(self.city_frame)
        self.city_label.setObjectName("city_label")
        self.verticalLayout_3.addWidget(self.city_label)
        self.city_line_edit = QLineEdit(self.city_frame)
        self.city_line_edit.setMinimumSize(QSize(0, 25))
        self.city_line_edit.setMaximumSize(QSize(16777215, 25))
        self.city_line_edit.setObjectName("city_line_edit")
        self.verticalLayout_3.addWidget(self.city_line_edit)
        self.verticalLayout_5.addWidget(self.city_frame)
        self.state_frame = QFrame(self.company_details_group_box)
        self.state_frame.setFrameShape(QFrame.StyledPanel)
        self.state_frame.setFrameShadow(QFrame.Raised)
        self.state_frame.setObjectName("state_frame")
        self.verticalLayout_4 = QVBoxLayout(self.state_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.state_label = QLabel(self.state_frame)
        self.state_label.setObjectName("state_label")
        self.verticalLayout_4.addWidget(self.state_label)
        self.state_combo_box = QComboBox(self.state_frame)
        self.state_combo_box.setMinimumSize(QSize(0, 25))
        self.state_combo_box.setMaximumSize(QSize(16777215, 25))
        self.state_combo_box.setObjectName("state_combo_box")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.verticalLayout_4.addWidget(self.state_combo_box)
        self.verticalLayout_5.addWidget(self.state_frame)
        self.verticalLayout_13.addWidget(self.company_details_group_box)
        self.position_details_group_box = QGroupBox(self.application_body_frame)
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.position_details_group_box.setFont(font)
        self.position_details_group_box.setFlat(True)
        self.position_details_group_box.setObjectName("position_details_group_box")
        self.verticalLayout_10 = QVBoxLayout(self.position_details_group_box)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.position_frame = QFrame(self.position_details_group_box)
        self.position_frame.setFrameShape(QFrame.StyledPanel)
        self.position_frame.setFrameShadow(QFrame.Raised)
        self.position_frame.setObjectName("position_frame")
        self.verticalLayout_6 = QVBoxLayout(self.position_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.position_label = QLabel(self.position_frame)
        self.position_label.setObjectName("position_label")
        self.verticalLayout_6.addWidget(self.position_label)
        self.position_line_edit = QLineEdit(self.position_frame)
        self.position_line_edit.setMinimumSize(QSize(0, 25))
        self.position_line_edit.setMaximumSize(QSize(16777215, 25))
        self.position_line_edit.setObjectName("position_line_edit")
        self.verticalLayout_6.addWidget(self.position_line_edit)
        self.verticalLayout_10.addWidget(self.position_frame)
        self.work_style_frame = QFrame(self.position_details_group_box)
        self.work_style_frame.setFrameShape(QFrame.StyledPanel)
        self.work_style_frame.setFrameShadow(QFrame.Raised)
        self.work_style_frame.setObjectName("work_style_frame")
        self.verticalLayout_7 = QVBoxLayout(self.work_style_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.work_style_label = QLabel(self.work_style_frame)
        self.work_style_label.setObjectName("work_style_label")
        self.verticalLayout_7.addWidget(self.work_style_label)
        self.work_style_combo_box = QComboBox(self.work_style_frame)
        self.work_style_combo_box.setMinimumSize(QSize(0, 25))
        self.work_style_combo_box.setMaximumSize(QSize(16777215, 25))
        self.work_style_combo_box.setObjectName("work_style_combo_box")
        self.work_style_combo_box.addItem("")
        self.work_style_combo_box.addItem("")
        self.work_style_combo_box.addItem("")
        self.work_style_combo_box.addItem("")
        self.verticalLayout_7.addWidget(self.work_style_combo_box)
        self.verticalLayout_10.addWidget(self.work_style_frame)
        self.employment_status_frame = QFrame(self.position_details_group_box)
        self.employment_status_frame.setFrameShape(QFrame.StyledPanel)
        self.employment_status_frame.setFrameShadow(QFrame.Raised)
        self.employment_status_frame.setObjectName("employment_status_frame")
        self.verticalLayout_8 = QVBoxLayout(self.employment_status_frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.employment_status_label = QLabel(self.employment_status_frame)
        self.employment_status_label.setObjectName("employment_status_label")
        self.verticalLayout_8.addWidget(self.employment_status_label)
        self.employment_status_combo_box = QComboBox(self.employment_status_frame)
        self.employment_status_combo_box.setMinimumSize(QSize(0, 25))
        self.employment_status_combo_box.setMaximumSize(QSize(16777215, 25))
        self.employment_status_combo_box.setObjectName("employment_status_combo_box")
        self.employment_status_combo_box.addItem("")
        self.employment_status_combo_box.addItem("")
        self.employment_status_combo_box.addItem("")
        self.employment_status_combo_box.addItem("")
        self.employment_status_combo_box.addItem("")
        self.employment_status_combo_box.addItem("")
        self.employment_status_combo_box.addItem("")
        self.employment_status_combo_box.addItem("")
        self.employment_status_combo_box.addItem("")
        self.verticalLayout_8.addWidget(self.employment_status_combo_box)
        self.verticalLayout_10.addWidget(self.employment_status_frame)
        self.job_details_frame = QFrame(self.position_details_group_box)
        self.job_details_frame.setFrameShape(QFrame.StyledPanel)
        self.job_details_frame.setFrameShadow(QFrame.Raised)
        self.job_details_frame.setObjectName("job_details_frame")
        self.verticalLayout_9 = QVBoxLayout(self.job_details_frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.job_description_label = QLabel(self.job_details_frame)
        self.job_description_label.setObjectName("job_description_label")
        self.verticalLayout_9.addWidget(self.job_description_label)
        self.job_description_plain_text_edit = QPlainTextEdit(self.job_details_frame)
        self.job_description_plain_text_edit.setMinimumSize(QSize(0, 250))
        self.job_description_plain_text_edit.setMaximumSize(QSize(16777215, 250))
        font = QFont()
        font.setPointSize(10)
        self.job_description_plain_text_edit.setFont(font)
        self.job_description_plain_text_edit.setObjectName("job_description_plain_text_edit")
        self.verticalLayout_9.addWidget(self.job_description_plain_text_edit)
        self.verticalLayout_10.addWidget(self.job_details_frame)
        self.verticalLayout_13.addWidget(self.position_details_group_box)
        self.contacts_information_group_box = QGroupBox(self.application_body_frame)
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.contacts_information_group_box.setFont(font)
        self.contacts_information_group_box.setFlat(True)
        self.contacts_information_group_box.setObjectName("contacts_information_group_box")
        self.verticalLayout_11 = QVBoxLayout(self.contacts_information_group_box)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.contacts_table_widget = QTableWidget(self.contacts_information_group_box)
        self.contacts_table_widget.setMinimumSize(QSize(0, 150))
        self.contacts_table_widget.setMaximumSize(QSize(16777215, 150))
        font = QFont()
        font.setPointSize(10)
        self.contacts_table_widget.setFont(font)
        self.contacts_table_widget.setObjectName("contacts_table_widget")
        self.contacts_table_widget.setColumnCount(5)
        self.contacts_table_widget.setRowCount(0)
        item = QTableWidgetItem()
        self.contacts_table_widget.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.contacts_table_widget.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.contacts_table_widget.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.contacts_table_widget.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.contacts_table_widget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_11.addWidget(self.contacts_table_widget)
        self.contacts_information_actions_frame = QFrame(self.contacts_information_group_box)
        self.contacts_information_actions_frame.setFrameShape(QFrame.StyledPanel)
        self.contacts_information_actions_frame.setFrameShadow(QFrame.Raised)
        self.contacts_information_actions_frame.setObjectName("contacts_information_actions_frame")
        self.horizontalLayout = QHBoxLayout(self.contacts_information_actions_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QSpacerItem(123, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.add_contact_button = QPushButton(self.contacts_information_actions_frame)
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.add_contact_button.setFont(font)
        self.add_contact_button.setObjectName("add_contact_button")
        self.horizontalLayout.addWidget(self.add_contact_button)
        spacerItem1 = QSpacerItem(122, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_11.addWidget(self.contacts_information_actions_frame)
        self.verticalLayout_13.addWidget(self.contacts_information_group_box)
        self.application_status_history_group_box = QGroupBox(self.application_body_frame)
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.application_status_history_group_box.setFont(font)
        self.application_status_history_group_box.setFlat(True)
        self.application_status_history_group_box.setObjectName("application_status_history_group_box")
        self.verticalLayout_12 = QVBoxLayout(self.application_status_history_group_box)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.application_status_history_table_widget = QTableWidget(self.application_status_history_group_box)
        self.application_status_history_table_widget.setMinimumSize(QSize(0, 150))
        self.application_status_history_table_widget.setMaximumSize(QSize(16777215, 150))
        font = QFont()
        font.setPointSize(10)
        self.application_status_history_table_widget.setFont(font)
        self.application_status_history_table_widget.setObjectName("application_status_history_table_widget")
        self.application_status_history_table_widget.setColumnCount(2)
        self.application_status_history_table_widget.setRowCount(0)
        item = QTableWidgetItem()
        self.application_status_history_table_widget.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.application_status_history_table_widget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_12.addWidget(self.application_status_history_table_widget)
        self.application_status_history_actions_frame = QFrame(self.application_status_history_group_box)
        self.application_status_history_actions_frame.setFrameShape(QFrame.StyledPanel)
        self.application_status_history_actions_frame.setFrameShadow(QFrame.Raised)
        self.application_status_history_actions_frame.setObjectName("application_status_history_actions_frame")
        self.horizontalLayout_2 = QHBoxLayout(self.application_status_history_actions_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QComboBox(self.application_status_history_actions_frame)
        self.comboBox.setMinimumSize(QSize(0, 25))
        self.comboBox.setMaximumSize(QSize(16777215, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.dateEdit = QDateEdit(self.application_status_history_actions_frame)
        self.dateEdit.setMinimumSize(QSize(0, 25))
        self.dateEdit.setMaximumSize(QSize(75, 25))
        self.dateEdit.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.dateEdit.setMinimumDateTime(QDateTime(QDate(2024, 1, 1), QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QDate(2124, 12, 31))
        self.dateEdit.setMinimumDate(QDate(2024, 1, 1))
        self.dateEdit.setCurrentSection(QDateTimeEdit.MonthSection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.add_status_button = QPushButton(self.application_status_history_actions_frame)
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.add_status_button.setFont(font)
        self.add_status_button.setObjectName("add_status_button")
        self.horizontalLayout_2.addWidget(self.add_status_button)
        self.verticalLayout_12.addWidget(self.application_status_history_actions_frame)
        self.verticalLayout_13.addWidget(self.application_status_history_group_box)
        self.error_message_frame = QFrame(self.application_body_frame)
        self.error_message_frame.setFrameShape(QFrame.StyledPanel)
        self.error_message_frame.setFrameShadow(QFrame.Raised)
        self.error_message_frame.setObjectName("error_message_frame")
        self.verticalLayout_14 = QVBoxLayout(self.error_message_frame)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.error_message = QLabel(self.error_message_frame)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.error_message.setFont(font)
        self.error_message.setStyleSheet("color: rgb(170, 0, 0);")
        self.error_message.setText("")
        self.error_message.setAlignment(Qt.AlignCenter)
        self.error_message.setObjectName("error_message")
        self.verticalLayout_14.addWidget(self.error_message)
        self.verticalLayout_13.addWidget(self.error_message_frame)
        self.application_body_actions_frame = QFrame(self.application_body_frame)
        self.application_body_actions_frame.setStyleSheet("QPushButton {\n"
"padding: 15px 35px;\n"
"}")
        self.application_body_actions_frame.setFrameShape(QFrame.StyledPanel)
        self.application_body_actions_frame.setFrameShadow(QFrame.Raised)
        self.application_body_actions_frame.setObjectName("application_body_actions_frame")
        self.horizontalLayout_3 = QHBoxLayout(self.application_body_actions_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(24)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QSpacerItem(51, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.save_button = QPushButton(self.application_body_actions_frame)
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("QPushButton {\n"
"background-color: rgb(46, 196, 89);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:Hover {\n"
"background-color:rgb(0, 113, 49);\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(46, 196, 89);\n"
"}")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_3.addWidget(self.save_button)
        self.clear_button = QPushButton(self.application_body_actions_frame)
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("QPushButton {\n"
"background-color: rgb(196, 46, 68);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:Hover {\n"
"background-color: rgb(137, 28, 48);\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"background-color: rgb(196, 46, 68);\n"
"}")
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_3.addWidget(self.clear_button)
        spacerItem3 = QSpacerItem(51, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_13.addWidget(self.application_body_actions_frame)
        self.scrikkAreaWidgetContents_layout.addWidget(self.application_body_frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.centralwidget_layout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.application_title_label.setText(_translate("MainWindow", "NEW APPLICATION"))
        self.company_details_group_box.setTitle(_translate("MainWindow", "Company Details"))
        self.company_label.setText(_translate("MainWindow", "Company:"))
        self.city_label.setText(_translate("MainWindow", "City:"))
        self.state_label.setText(_translate("MainWindow", "State:"))
        self.state_combo_box.setItemText(0, _translate("MainWindow", "-"))
        self.state_combo_box.setItemText(1, _translate("MainWindow", "Alabama"))
        self.state_combo_box.setItemText(2, _translate("MainWindow", "Alaska"))
        self.state_combo_box.setItemText(3, _translate("MainWindow", "Arizona"))
        self.state_combo_box.setItemText(4, _translate("MainWindow", "Arkansas"))
        self.state_combo_box.setItemText(5, _translate("MainWindow", "California"))
        self.state_combo_box.setItemText(6, _translate("MainWindow", "Colorado"))
        self.state_combo_box.setItemText(7, _translate("MainWindow", "Connecticut"))
        self.state_combo_box.setItemText(8, _translate("MainWindow", "Delaware"))
        self.state_combo_box.setItemText(9, _translate("MainWindow", "Florida"))
        self.state_combo_box.setItemText(10, _translate("MainWindow", "Georgia"))
        self.state_combo_box.setItemText(11, _translate("MainWindow", "Hawaii"))
        self.state_combo_box.setItemText(12, _translate("MainWindow", "Idaho"))
        self.state_combo_box.setItemText(13, _translate("MainWindow", "Illinois"))
        self.state_combo_box.setItemText(14, _translate("MainWindow", "Indiana"))
        self.state_combo_box.setItemText(15, _translate("MainWindow", "Iowa"))
        self.state_combo_box.setItemText(16, _translate("MainWindow", "Kansas"))
        self.state_combo_box.setItemText(17, _translate("MainWindow", "Kentucky"))
        self.state_combo_box.setItemText(18, _translate("MainWindow", "Louisiana"))
        self.state_combo_box.setItemText(19, _translate("MainWindow", "Maine"))
        self.state_combo_box.setItemText(20, _translate("MainWindow", "Maryland"))
        self.state_combo_box.setItemText(21, _translate("MainWindow", "Massachusetts"))
        self.state_combo_box.setItemText(22, _translate("MainWindow", "Michigan"))
        self.state_combo_box.setItemText(23, _translate("MainWindow", "Minnesota"))
        self.state_combo_box.setItemText(24, _translate("MainWindow", "Mississippi"))
        self.state_combo_box.setItemText(25, _translate("MainWindow", "Missouri"))
        self.state_combo_box.setItemText(26, _translate("MainWindow", "Montana"))
        self.state_combo_box.setItemText(27, _translate("MainWindow", "Nebraska"))
        self.state_combo_box.setItemText(28, _translate("MainWindow", "New Hampshire"))
        self.state_combo_box.setItemText(29, _translate("MainWindow", "New Jersey"))
        self.state_combo_box.setItemText(30, _translate("MainWindow", "New Mexico"))
        self.state_combo_box.setItemText(31, _translate("MainWindow", "New York"))
        self.state_combo_box.setItemText(32, _translate("MainWindow", "North Carolina"))
        self.state_combo_box.setItemText(33, _translate("MainWindow", "North Dakota"))
        self.state_combo_box.setItemText(34, _translate("MainWindow", "Ohio"))
        self.state_combo_box.setItemText(35, _translate("MainWindow", "Oklahoma"))
        self.state_combo_box.setItemText(36, _translate("MainWindow", "Oregon"))
        self.state_combo_box.setItemText(37, _translate("MainWindow", "Pennsylvania"))
        self.state_combo_box.setItemText(38, _translate("MainWindow", "Rhode Island"))
        self.state_combo_box.setItemText(39, _translate("MainWindow", "South Carolina"))
        self.state_combo_box.setItemText(40, _translate("MainWindow", "South Dakota"))
        self.state_combo_box.setItemText(41, _translate("MainWindow", "Tennessee"))
        self.state_combo_box.setItemText(42, _translate("MainWindow", "Texas"))
        self.state_combo_box.setItemText(43, _translate("MainWindow", "Utah"))
        self.state_combo_box.setItemText(44, _translate("MainWindow", "Vermont"))
        self.state_combo_box.setItemText(45, _translate("MainWindow", "Virginia"))
        self.state_combo_box.setItemText(46, _translate("MainWindow", "Washington"))
        self.state_combo_box.setItemText(47, _translate("MainWindow", "West Virginia"))
        self.state_combo_box.setItemText(48, _translate("MainWindow", "Wisconsin"))
        self.state_combo_box.setItemText(49, _translate("MainWindow", "Wyoming"))
        self.position_details_group_box.setTitle(_translate("MainWindow", "Position Details"))
        self.position_label.setText(_translate("MainWindow", "Position:"))
        self.work_style_label.setText(_translate("MainWindow", "Work Style:"))
        self.work_style_combo_box.setItemText(0, _translate("MainWindow", "-"))
        self.work_style_combo_box.setItemText(1, _translate("MainWindow", "On-Site"))
        self.work_style_combo_box.setItemText(2, _translate("MainWindow", "Remote"))
        self.work_style_combo_box.setItemText(3, _translate("MainWindow", "Hybrid"))
        self.employment_status_label.setText(_translate("MainWindow", "Employment Status:"))
        self.employment_status_combo_box.setItemText(0, _translate("MainWindow", "-"))
        self.employment_status_combo_box.setItemText(1, _translate("MainWindow", "Full-Time"))
        self.employment_status_combo_box.setItemText(2, _translate("MainWindow", "Part-Time"))
        self.employment_status_combo_box.setItemText(3, _translate("MainWindow", "Contract"))
        self.employment_status_combo_box.setItemText(4, _translate("MainWindow", "Freelance"))
        self.employment_status_combo_box.setItemText(5, _translate("MainWindow", "Temporary"))
        self.employment_status_combo_box.setItemText(6, _translate("MainWindow", "Volunteer"))
        self.employment_status_combo_box.setItemText(7, _translate("MainWindow", "Co-Op"))
        self.employment_status_combo_box.setItemText(8, _translate("MainWindow", "Internship"))
        self.job_description_label.setText(_translate("MainWindow", "Job Description"))
        self.contacts_information_group_box.setTitle(_translate("MainWindow", "Contacts Information"))
        item = self.contacts_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Position"))
        item = self.contacts_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.contacts_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.contacts_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.contacts_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Phone Number"))
        self.add_contact_button.setText(_translate("MainWindow", "Add Contact"))
        self.application_status_history_group_box.setTitle(_translate("MainWindow", "Application Status History"))
        item = self.application_status_history_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Status"))
        item = self.application_status_history_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        self.comboBox.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Application Submitted"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Screening Interview"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Technical Interview"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Job Offer"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Application Rejected"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "M-d-yyyy"))
        self.add_status_button.setText(_translate("MainWindow", "Add Status"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
